### PR TITLE
Update travis build, use latest release

### PR DESCRIPTION
**Pull request by vivekiitkgp**
#222 
Signed-off-by: Vivek Rai <vivekraiiitkgp@gmail.com>

### CODE REVIEW

**Comment by yeban** [comment]
Thanks!

**Comment by yeban** [comment]
Ok. This has a few problems (apart from the one I fixed - fa73005940b1d75866ad5b3cec40ae5d0aeb03a6). It builds 1.0.4, not 1.0.5 which is the latest. This is because I forked off the new release into 1.0.x branch so that dev for 1.1 can continue on master. @vivekiitkgp would you be able to address this in travis.yml?

**Comment by vivekiitkgp** [comment]
@yeban I didn't prefer checking out to a particular release because it is dependent on version numbering. Later if we make a 1.2.x release, it will require a change. Although, it is not a big deal.

Also, I had noticed the current release being shown as 1.0.4 instead of 1.0.5. It can be easily fixed by drafting a new release, I presume.

**Comment by yeban** [comment]
Ok. After some trial and error I have settled on this - https://github.com/wurmlab/sequenceserver/blob/master/.travis.yml. Applying the updated Travis config to 1.0.x branch has it passing on Travis - hopefully the badge will update soon (both in README and on biogems)

We will have to update Travis config when master is ready. But that's okay. And in future (for 1.2.x etc.), this scenario can hopefully be avoided.

**Pull request merged**
