### PR TITLE
add SEO plugin, update page.html and config

### PR DESCRIPTION
**Pull request by discoform**
merge into `wurmlab/sequenceserver` `gh-pages` branch

- Added [Jekyll SEO tag](https://github.com/jekyll/jekyll-seo-tag) to `Gemfile`
- Added Jekyll SEO tag to plugins in `_config.yml`
- Update `_config.yml` with `title:`, `description:`  and `url:`
- updated  `_layouts/page.html` to include `{% seo %}` , plus added `!DOCTYPE` and `lang` attribute
- Local testing looks good.

### CODE REVIEW

**Comment by yeban** [comment]
This conflicts with #539 and vice versa.

**Comment by discoform** [comment]
@yeban I'm happy to address any conflicts, though I believe we should be able to merge this and afterward we can evaluate any conflicts in merging https://github.com/wurmlab/sequenceserver/pull/539 (unless I'm missing something)

**Comment by yeban** [comment]
@discoform Okay, done

**Comment by discoform** [comment]
Thanks, @yeban. I see the conflicts now. I'll work on resolving them today and follow up.

**Comment by discoform** [comment]
Hi @yeban quick update; I'm going to (hopefully) make this a little easier on us by merging my commits to my own fork at https://github.com/discoform/sequenceserver/tree/gh-pages and the PR from that.

You can see the work from previous PRs has been added there now.  Let me know if you have any thoughts or objections to this idea, otherwise I'll submit a new PR from there on Monday.

**Pull request merged**
