### PR TITLE
Add "Share results" section to sidebar and "send URL by email" functionality. - Update sidebar.js

### PR DESCRIPTION
**Pull request by dpavam**
Adds a new "Share results section to the sidebar. Within this section, a "Send by email" button enables users to send the URL, search id, and the first 15 databases of their results through email. 

This also resolves some issues pointed out here: #579. A different CSS class ('sharing-panel) has been given to the sidebar and the sentence case has been preserved. The "Copy URL to clipboard" has been removed from this version. 

Unit tests check the contents of the "mailto" message.

### CODE REVIEW

**Comment by yannickwurm** [comment]
Thanks Diego. 
Does this one supersede #579? If so, can you please close 579?

**Comment by yannickwurm** [comment]
Hi @dpavam - I'm unsure what to do about the conflicting files here?

**Comment by dpavam** [comment]
Hi @yannickwurm, would creating a new PR with all of this on the ES6 version solve it?

**Comment by yannickwurm** [comment]
Probably :)

**Comment by dpavam** [comment]
I'm on it, the version is ready. Currently fixing the conflicts between my fork and the original.

**Pull request closed without merging**
