### PR TITLE
fix sidebar bug - #176

### PR DESCRIPTION
**Pull request by IsmailM**
Fixes Sidebar bug - #176

### CODE REVIEW

**Comment by yeban** [comment]
We use fixed container width: 970 px at window width >= 992 px and 1170 px at window width >=1200 px. Sidebar takes 3 out of 12 columns in the grid: 25% of container width. Thus I would prefer setting sidebar width explicitly in CSS at 242.5 px and 292.5 px depending on screen size, using `@media` query. What do you think?

**Comment by IsmailM** [comment]
Agreed - Since the Sidebar is within a `col-md-3`, the width is automatically set by Bootstap. And as such there is no need to add any CSS. Thus, I simply removed the JS line that set the sidebar width.

**Comment by yeban** [comment]
Width should be set for `position: fixed` elements. And we thus should for `.sidebar`. If you remove the JS line that sets the width, you will see bottom borders in the sidebar shrink and grow as the sidebar is affixed and removed.

**Comment by IsmailM** [comment]
The sidebar width is now set by CSS as requested.

**Comment by yeban** [comment]
This is great. Please could you squash the commits? And don't build the assets - will do it during release.

**Comment by IsmailM** [comment]
Done

**Comment by yeban** [comment]
This doesn't seem to work: if sidebar was initially hidden, and then made to appear by resizing the window, the width is set right but the sidebar is no longer affixed.

**Comment by yeban** [comment]
I patched that (1c78e31947e4ece90eb7250a00a6b04206eefca5).

**Pull request merged**
