### PR TITLE
Improve IP/hostname detection on EC2 (first try)

### PR DESCRIPTION
**Pull request by tuxinaut**
It's not the best code on planet earth but it does what it's supposed to do.

I would plan to improve the code after this PR and even though Hacktober is over ;)

Related to #488

### CODE REVIEW

**Comment by yeban** [comment]
Thanks. Can you help me understand the rationale of your approach? Did you consider the possibility that (in line 254) the public IP may be included in the array returned by `Socket.ip_address_list`, but is not being returned by `.find` because:
1. both public and private IP will match the condition defined within `{}` and
2. if there are multiple matches, `find` returns the first match, and the first match just happens to be the private ip

**Comment by tuxinaut** [comment]
> Thanks. Can you help me understand the rationale of your approach? 

Yes, sure I will try my best. At first, I'm a bit biased regarding the AWS EC2 metadata service ;)

>  Did you consider the possibility that (in line 254) the public IP may be included in the array returned by Socket.ip_address_list, but is not being returned by .find because:

>  1.  both public and private IP will match the condition defined within {} and
>  2. if there are multiple matches, find returns the first match, and the first match just happens to be the private ip

Let me (re-)check this possibility.

**Comment by yeban** [comment]
Although I discovered the issue while working on AWS EC2, I think the problem is of a more general nature. Other cloud providers may also have a private and a public IP for their instances, and SequenceServer might fail to detect the right one. Thus a more general solution would be more preferable.

I think you will find that `Socket.ip_address_list` already includes the public ip (no, I have not tested that to be 100% sure). I also came across a method in Ruby's Addrinfo class that can help distinguish private IP: https://docs.ruby-lang.org/en/2.1.0/Addrinfo.html#method-i-ipv4_private-3F.

**Comment by tuxinaut** [comment]
I will try to have another look this weekend.

**Comment by yeban** [comment]
I will close this for now.

**Pull request closed without merging**
