### PR TITLE
Revert "Update React and convert react components to es6 class components syntax"

### PR DESCRIPTION
**Pull request by yannickwurm**
Reverts wurmlab/sequenceserver#583

### CODE REVIEW

**Comment by yeban** [comment]
Why? Does it mean #583 should be reopened? Updated Dockerfile and README (new non-JSPM build instructions) are missing in #583.

**Comment by yeban** [comment]
And also #556

**Comment by yannickwurm** [comment]
No - I tight I’d pressed the wrong button. And that it didn’t show the individual commits. But baby Brain may have f-ed my perception.

I think it should show lazy-poets individual commits.

Typos courtesy of my iPhone

On 21 May 2022, at 08:34, Anurag Priyam ***@***.***> wrote:

﻿

Why? Does it mean #583<https://github.com/wurmlab/sequenceserver/pull/583> should be reopened? Updated Dockerfile and README (new non-JSPM build instructions) are missing in #583<https://github.com/wurmlab/sequenceserver/pull/583>.

**Comment by yannickwurm** [comment]
Ok  - I rebased to eliminate this revert

**Pull request merged**
