### PR TITLE
Redudancy removal #485

### PR DESCRIPTION
**Pull request by joko3ono**
I do test using sending 2 identiq query, it will give me redundant results, but when I do download it giving me this error message on fasta file

```
# ERROR: incorrect number of sequences found.
# You requested 14 sequence(s) with the following
# identifiers:
#   SI2.2.0_06267, ref|XM_039451179.1|, ref|XM_039451177.1|, ref|XM_039451188.1|, ref|XM_039451192.1|, ref|XM_011159896.3|, ref|XM_039451197.1|, SI2.2.0_06267, ref|XM_039451179.1|, ref|XM_039451177.1|, ref|XM_039451188.1|, ref|XM_039451192.1|, ref|XM_011159896.3|, ref|XM_039451197.1|
# from the following databases:
#   Hereis assembly one 2022-04 , sequenceserver-18 hits
# but we found 7 sequence(s).
# 
# This is likley due to a problem with how databases are formatted.
# Please share this text with the person managing this website.
# 
# If you are the admin and are confident that your databases are
# correctly formatted, you have likely encountered a weird bug.
# In this case, please raise an issue at:
# https://github.com/wurmlab/sequenceserver/issues
# 
# If any sequences were retrieved, you can find them below
# (but some may be incorrect, so be careful!)
```

### CODE REVIEW

**Comment by tadast** [comment]
So this passes all sequence ids to blast and only when it's done, looks for redundant sequences. @yannickwurm am I right in thinking that we could do this check earlier and eliminate redundant sequence **IDs** before sending them to blast?

If that's the case, it would be easiest to do it as early as possible - in the frontend where we're compiling sequence IDs to post to the backend.

@joko3ono it would also be nice to get some rspec tests for this change.

**Comment by yannickwurm** [comment]
Yes, Tadas as you suggest it would be better to Remove redundancy beforehand. 
Once we’ve done that, we should not remove it done second time

**Comment by joko3ono** [comment]
@tadast logic changed just before blast, if there is duplicate query, we will only take the first one and ignore the last one

**Comment by tadast** [comment]
Ok this is interesting, you're actually looking at the query sequence **values**, not **identifiers**, and removing duplicates based on value uniqueness. 

Originally I suggested making the list of requested sequence IDs unique before the user downloads them [here](https://github.com/wurmlab/sequenceserver/blob/57c4fc22e1e5d7d85c81ba727133ed1c97da27b1/lib/sequenceserver/routes.rb#L159) or even [here](https://github.com/wurmlab/sequenceserver/blob/57c4fc22e1e5d7d85c81ba727133ed1c97da27b1/public/js/download_fasta.js#L8) to address the immediate issue, but this takes it a step further and eliminates duplicates before running BLAST.

I feel like the user could still make an error and have something like:
```
> Query_1
ACGT
> Query_1
AGGT
```

i.e. the sequences are unique, but IDs are mistakenly duplicated.

Similarly, the solution currently proposed ignores duplicate sequences even if their IDs are unique, only considering the first one.

I'd imagine there are performance implications for large queries too when comparing sequences in ruby.

@yannickwurm @djleite what do you think about this?

**Comment by yannickwurm** [comment]
We should indeed deduplicate based on sequence identifiers. (those we have in the blast report). 

We should do this prior to any retrieval.

**Comment by tadast** [comment]
@joko3ono sounds like https://github.com/wurmlab/sequenceserver/blob/57c4fc22e1e5d7d85c81ba727133ed1c97da27b1/lib/sequenceserver/routes.rb#L159 is the right place then. You can discard this PR or replace the commits, whichever is easier.

**Comment by joko3ono** [comment]
@tadast I will close this PR
use this PR instead #803

**Pull request closed without merging**
