### PR TITLE
Fix regex to detect multipart database

### PR DESCRIPTION
**Pull request by loraine-gueguen**
fix https://github.com/wurmlab/sequenceserver/issues/465

But I am not sure to merge on the right branch.

### CODE REVIEW

**Comment by loraine-gueguen** [comment]
The travis test fails with "Connection timed out" during `wget -c "ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.30/ncbi-blast-2.2.30+-x64-linux.tar.gz"`. However, I have tested and it seems ok now. Could you launch the test again ?

**Comment by yeban** [comment]
Don't worry about that - it will likely fail again. I need to get in touch with people at Travis to work out a proper solution for that one.

**Comment by yeban** [comment]
Thanks. I will make a gem release shortly.

**Comment by yeban** [comment]
Release done
- https://github.com/wurmlab/sequenceserver/releases/tag/1.0.14
- https://rubygems.org/gems/sequenceserver

**Pull request merged**
